apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
{{ $serivceName := printf "%s-%s" "registry" .Release.Name }}
{{ range $host :=.Values.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $serivceName }}
                port:
                  number: 5000
{{ end }}