apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.baseHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry-{{ .Release.Name }}
                port:
                  number: 5000
