apiVersion: v1
kind: Service
metadata:
  name: registry-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - name: http-registry
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: registry-{{ .Release.Name }}